### ISSUE TITLE
Rewrite of Crypto parts

### ISSUE THREAD

**Issue by halilozercan** [halilozercan/halocoin#1]
There are still parts that are left untouched from basiccoin. Most important ones are peer checking, peer ranking and crypto algorithms. Before moving onto forking this repository for Coinami 2, these parts need to be handled.

What is left before fork:
- Python 3 Integration. Python 2 support will be dropped.
- New Peer Ranking and Discovery
- Simple Cryptographic tools for Symmetric Key Generation, Address Encoding, Signing

**Comment by justinba1010** [comment]
Have you tried https://github.com/AntonKueltz/fastecdsa?
